import React, {useEffect, type ReactNode} from 'react';
import OriginalLayout from '@theme-original/DocItem/Layout';
import {useDoc} from '@docusaurus/plugin-content-docs/client';
import type {Props} from '@theme/DocItem/Layout';
import {pushRecent, crumbFromUrl} from '@site/src/lib/recently-viewed';

/**
 * Wraps the stock DocItem layout so every viewed article gets pushed into the
 * localStorage ring buffer behind "Pick up where you left off" on the landing.
 * The skipped paths cover landing scaffolding (homepage, persona pages,
 * autogenerated section indexes) so they don't pollute the user's recents.
 */
const SKIP_PREFIXES = ['/path/', '/search', '/modules', '/reference', '/release-notes'];
const SKIP_EXACT = new Set(['/', '/modules', '/reference', '/release-notes']);

export default function DocItemLayoutWrapper(props: Props): ReactNode {
  const {metadata, frontMatter} = useDoc();
  const url = metadata?.permalink ?? '';
  const title = (frontMatter as {title?: string})?.title ?? metadata?.title ?? '';

  useEffect(() => {
    if (!url || !title) return;
    if (SKIP_EXACT.has(url)) return;
    // Skip the autogenerated section index pages (no nested path under the
    // section). e.g. /modules itself, but not /modules/quiz/...
    if (SKIP_PREFIXES.some((p) => url === p || url === p.replace(/\/$/, ''))) return;
    if (url.startsWith('/path/')) return;
    pushRecent({
      url,
      title,
      crumb: crumbFromUrl(url),
    });
  }, [url, title]);

  return <OriginalLayout {...props} />;
}
