import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {NAV_SECTIONS} from './src/nav-sections';

/**
 * Topic-first IA - see plans/help-menu-redesign.md.
 *
 * The top-level sections (label, slug, description, role gate) are declared
 * once in src/nav-sections.ts and shared with the mobile hamburger menu
 * (src/theme/Navbar/MobileSidebar/PrimaryMenu) so the two cannot drift. Each
 * section contains an autogenerated subtree; per-module privilege gates live in
 * docs/modules/<m>/_category_.json so adding a new module = create a folder +
 * _category_.json, no sidebars.ts edit.
 *
 * Gate resolution lives in src/access-policy.ts (isAllowed) and is consumed by
 * the swizzled DocSidebarItem/{Category,Link} wrappers. The server-side guard
 * in server.js + plugins/access-gate-emit.js reads the same customProps tree.
 */

const sidebars: SidebarsConfig = {
  tutorialSidebar: NAV_SECTIONS.map((section) => ({
    type: 'category' as const,
    label: section.label,
    collapsed: section.collapsed ?? true,
    link: section.linkDocId
      ? {type: 'doc' as const, id: section.linkDocId}
      : {
          type: 'generated-index' as const,
          title: section.label,
          description: section.description,
          slug: section.slug,
        },
    customProps: section.gate,
    items: [{type: 'autogenerated' as const, dirName: section.id}],
  })),
};

export default sidebars;
