import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar access gating:
 *   customProps.roles      — viewer must hold at least one of these roles
 *   customProps.privilege  — viewer's org must have this org privilege
 *   customProps.anyPrivilege — viewer's org must have at least one of these
 *
 * Resolution lives in src/access-policy.ts (isAllowed) and is consumed by the
 * swizzled DocSidebarItem/{Category,Link} wrappers. Role/privilege keys mirror
 * smartwinnr_prd: roles from authentication policies, privileges from
 * organizations.server.model.js.
 */

const ALL_ROLES = ['user', 'manager', 'editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];
const MANAGER_PLUS_ROLES = ['manager', 'editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];
const STAFF_ROLES = ['editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];
const ADMIN_ONLY_ROLES = ['admin', 'orgadmin', 'lamadmin', 'superadmin'];

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      customProps: {roles: ALL_ROLES},
      items: [{type: 'autogenerated', dirName: 'overview'}],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      customProps: {roles: ALL_ROLES},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Announcements',
      collapsed: true,
      customProps: {roles: ALL_ROLES},
      items: [{type: 'autogenerated', dirName: 'announcements'}],
    },
    {
      type: 'category',
      label: 'User Guide',
      collapsed: true,
      customProps: {roles: ALL_ROLES},
      items: [
        // Autogen recursively includes user-guide/ai-coaching/ as a sub-category.
        // The gate for AI Coaching lives in docs/user-guide/ai-coaching/_category_.json
        // (defining a second manual entry here would create a duplicate sidebar item).
        {type: 'autogenerated', dirName: 'user-guide'},
        {type: 'autogenerated', dirName: 'help-support'},
        {type: 'autogenerated', dirName: 'troubleshooting'},
      ],
    },
    {
      type: 'category',
      label: 'Manager Guide',
      collapsed: true,
      customProps: {roles: MANAGER_PLUS_ROLES, privilege: 'managerView'},
      items: [{type: 'autogenerated', dirName: 'manager-guide'}],
    },
    {
      type: 'category',
      label: 'Administrative Guide',
      collapsed: true,
      customProps: {roles: STAFF_ROLES},
      items: [
        {
          type: 'category',
          label: 'System Management',
          customProps: {roles: ADMIN_ONLY_ROLES},
          items: [{type: 'autogenerated', dirName: 'administration/system-management'}],
        },
        {
          type: 'category',
          label: 'Access Permissions',
          customProps: {roles: ADMIN_ONLY_ROLES},
          items: [{type: 'autogenerated', dirName: 'administration/access-permissions'}],
        },
        {
          type: 'category',
          label: 'Quiz Module',
          customProps: {roles: STAFF_ROLES, privilege: 'quiz'},
          items: [{type: 'autogenerated', dirName: 'administration/quiz-module'}],
        },
        {
          type: 'category',
          label: 'SmartPath Module',
          customProps: {roles: STAFF_ROLES, privilege: 'smartpaths'},
          items: [{type: 'autogenerated', dirName: 'administration/smartpath-module'}],
        },
        {
          type: 'category',
          label: 'SmartFeed Module',
          customProps: {roles: STAFF_ROLES, privilege: 'content'},
          items: [{type: 'autogenerated', dirName: 'administration/smartfeed-module'}],
        },
        {
          type: 'category',
          label: 'Video Coaching Module',
          customProps: {roles: STAFF_ROLES, privilege: 'coaching'},
          items: [{type: 'autogenerated', dirName: 'administration/video-coaching-module'}],
        },
        {
          type: 'category',
          label: 'Field Coaching Module',
          customProps: {roles: STAFF_ROLES, privilege: 'fCoaching'},
          items: [{type: 'autogenerated', dirName: 'administration/field-coaching-module'}],
        },
        {
          type: 'category',
          label: 'AI Coaching Module',
          customProps: {roles: STAFF_ROLES, privilege: 'aiCoaching'},
          items: [{type: 'autogenerated', dirName: 'administration/ai-coaching'}],
        },
        {
          type: 'category',
          label: 'Survey Module',
          customProps: {roles: STAFF_ROLES, privilege: 'survey'},
          items: [{type: 'autogenerated', dirName: 'administration/survey-module'}],
        },
        {
          type: 'category',
          label: 'Knowledge Hub Module',
          customProps: {roles: STAFF_ROLES, privilege: 'khub'},
          items: [{type: 'autogenerated', dirName: 'administration/knowledge-hub-module'}],
        },
        {
          type: 'category',
          label: 'Forms Module',
          customProps: {roles: STAFF_ROLES, privilege: 'forms'},
          items: [{type: 'autogenerated', dirName: 'administration/forms-module'}],
        },
        {
          type: 'category',
          label: 'KPI & Gamification',
          customProps: {roles: STAFF_ROLES, anyPrivilege: ['kpi', 'competitions', 'achievements']},
          items: [{type: 'autogenerated', dirName: 'administration/kpi-gamification'}],
        },
        {
          type: 'category',
          label: 'Reports & Analytics',
          customProps: {roles: STAFF_ROLES, anyPrivilege: ['learnerReport', 'adminReports', 'generatedReports']},
          items: [{type: 'autogenerated', dirName: 'administration/reports'}],
        },
        {
          type: 'category',
          label: 'Notifications & Chats',
          customProps: {roles: STAFF_ROLES, anyPrivilege: ['customNotifications', 'notifications', 'chat']},
          items: [{type: 'autogenerated', dirName: 'administration/notifications'}],
        },
        {
          type: 'category',
          label: 'Project Management',
          customProps: {roles: STAFF_ROLES, privilege: 'projectManagement'},
          items: [{type: 'autogenerated', dirName: 'administration/project-management'}],
        },
        {
          type: 'category',
          label: 'Cross-Module Features',
          customProps: {roles: STAFF_ROLES},
          items: [{type: 'autogenerated', dirName: 'administration/cross-module-features'}],
        },
      ],
    },
  ],
};

export default sidebars;
