import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '📝 Quiz & Assessments',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'quiz-assessments',
        },
      ],
    },
    {
      type: 'category',
      label: '🧠 MicroLearning & SmartFeeds',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'microlearning-smartfeeds',
        },
      ],
    },
    {
      type: 'category',
      label: '🛤️ Learning & SmartPaths',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'learning-smartpaths',
        },
      ],
    },
    {
      type: 'category',
      label: '📋 Forms & Data Collection',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'forms-data-collection',
        },
      ],
    },
    {
      type: 'category',
      label: '📚 Knowledge Hub',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'knowledge-hub',
        },
      ],
    },
    {
      type: 'category',
      label: '📊 Surveys & Feedback',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'surveys-feedback',
        },
      ],
    },
    {
      type: 'category',
      label: '📈 Analytics & Reporting',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'analytics-reporting',
        },
      ],
    },
    {
      type: 'category',
      label: '🏆 Competitions & Gamification',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'competitions-gamification',
        },
      ],
    },
    {
      type: 'category',
      label: '🎯 Coaching & Performance',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'coaching-performance',
        },
      ],
    },
    {
      type: 'category',
      label: '👑 Administration',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'administration',
        },
      ],
    },
    {
      type: 'category',
      label: '📱 Mobile & Platform Tools',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'mobile-platform-tools',
        },
      ],
    },
    {
      type: 'category',
      label: '🆘 Help & Support',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'help-support',
        },
      ],
    },
  ],
};

export default sidebars;