#!/usr/bin/env node
/**
 * Help-site IA migration - Phase 3 of plans/help-menu-redesign.md.
 *
 * What this script does (single, atomic pass):
 *   1. Renames legacy doc directories into the new topic-first layout via `git mv`.
 *      Modules collapse from docs/administration/<m>-module/ → docs/modules/<m>/.
 *   2. Writes per-section and per-module _category_.json files so the
 *      autogenerated sidebar inherits the right role/privilege gates.
 *   3. Emits data/redirects.json - a list of {from, to} pairs covering every
 *      moved article, so @docusaurus/plugin-client-redirects can keep
 *      previously-shared URLs alive.
 *
 * Conservative on purpose:
 *   • Articles are MOVED WHOLE, not bucketed into sub-sections. Sub-section
 *     classification (Create & Manage / Reports / Settings / etc.) is a
 *     follow-up content pass - there is no way to safely auto-classify 270
 *     articles by filename, so we don't try.
 *   • Frontmatter is left untouched.
 *   • The script REQUIRES a clean working tree (modulo the .docusaurus/ cache
 *     and known build artifacts) so the resulting commit is reviewable.
 *
 * Usage:
 *   node scripts/migrate-ia.js                # dry-run: prints the plan
 *   node scripts/migrate-ia.js --apply        # actually runs `git mv`
 */

'use strict';

const fs = require('fs');
const path = require('path');
const {execSync} = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');

const APPLY = process.argv.includes('--apply');

// ---- 1. Section + module taxonomy ----------------------------------------

const ALL_ROLES = ['user', 'manager', 'editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];
const MANAGER_PLUS_ROLES = ['manager', 'editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];
const EDITOR_PLUS_ROLES = ['editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];
const ADMIN_PLUS_ROLES = ['admin', 'orgadmin', 'lamadmin', 'superadmin'];

// New top-level sections (8). Each becomes docs/<dir>/_category_.json.
const SECTIONS = [
  {dir: 'get-started',         label: 'Get Started',         position: 1,  customProps: {roles: ALL_ROLES}},
  {dir: 'guides',              label: 'Guides',              position: 2,  customProps: {roles: ALL_ROLES}},
  {dir: 'modules',             label: 'Modules',             position: 3,  customProps: {roles: ALL_ROLES}},
  {dir: 'reports-and-analytics', label: 'Reports & Analytics', position: 4, customProps: {roles: MANAGER_PLUS_ROLES, anyPrivilege: ['learnerReport','adminReports','generatedReports','automatedReports','overAllDashboards']}},
  {dir: 'integrations',        label: 'Integrations',        position: 5,  customProps: {roles: ADMIN_PLUS_ROLES}},
  {dir: 'administration',      label: 'Administration',      position: 6,  customProps: {roles: ADMIN_PLUS_ROLES}},
  {dir: 'reference',           label: 'Reference',           position: 7,  customProps: {roles: ALL_ROLES}},
  {dir: 'release-notes',       label: 'Release Notes',       position: 8,  customProps: {roles: ALL_ROLES}},
];

// Per-module gates (mirrors current sidebars.ts customProps). Position drives
// the in-sidebar order under "Modules".
const MODULES = [
  {dir: 'quiz',              label: 'Quiz',                 position: 10, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'quiz'}},
  {dir: 'smartpath',         label: 'SmartPath',            position: 20, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'smartpaths'}},
  {dir: 'smartfeed',         label: 'SmartFeed',            position: 30, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'content'}},
  {dir: 'video-coaching',    label: 'Video Coaching',       position: 40, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'coaching'}},
  {dir: 'ai-coaching',       label: 'AI Coaching',          position: 50, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'aiCoaching'}},
  {dir: 'field-coaching',    label: 'Field Coaching',       position: 60, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'fCoaching'}},
  {dir: 'survey',            label: 'Survey',               position: 70, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'survey'}},
  {dir: 'knowledge-hub',     label: 'Knowledge Hub',        position: 80, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'khub'}},
  {dir: 'forms',             label: 'Forms',                position: 90, customProps: {roles: EDITOR_PLUS_ROLES, privilege: 'forms'}},
  {dir: 'kpi-gamification',  label: 'KPI & Gamification',   position: 100, customProps: {roles: EDITOR_PLUS_ROLES, anyPrivilege: ['kpi','competitions','achievements']}},
  {dir: 'notifications',     label: 'Notifications & Chat', position: 110, customProps: {roles: EDITOR_PLUS_ROLES, anyPrivilege: ['customNotifications','notifications','chat']}},
  {dir: 'cross-module',      label: 'Cross-Module Features',position: 130, customProps: {roles: EDITOR_PLUS_ROLES}},
];

// Directory moves: legacy → new. Order matters when sources nest.
const MOVES = [
  // Top-level consolidations
  {from: 'overview',          to: 'get-started/overview'},
  {from: 'getting-started',   to: 'get-started/onboarding'},
  {from: 'announcements',     to: 'release-notes/announcements'},
  {from: 'user-guide',        to: 'guides/learner'},
  {from: 'manager-guide',     to: 'guides/manager'},
  {from: 'help-support',      to: 'reference/help-support'},
  {from: 'troubleshooting',   to: 'reference/troubleshooting'},

  // Module-by-module (drop the "-module" suffix; collapse under docs/modules/)
  {from: 'administration/quiz-module',           to: 'modules/quiz'},
  {from: 'administration/smartpath-module',      to: 'modules/smartpath'},
  {from: 'administration/smartfeed-module',      to: 'modules/smartfeed'},
  {from: 'administration/video-coaching-module', to: 'modules/video-coaching'},
  {from: 'administration/field-coaching-module', to: 'modules/field-coaching'},
  {from: 'administration/ai-coaching',           to: 'modules/ai-coaching'},
  {from: 'administration/survey-module',         to: 'modules/survey'},
  {from: 'administration/knowledge-hub-module',  to: 'modules/knowledge-hub'},
  {from: 'administration/forms-module',          to: 'modules/forms'},
  {from: 'administration/kpi-gamification',      to: 'modules/kpi-gamification'},
  {from: 'administration/notifications',         to: 'modules/notifications'},
  {from: 'administration/cross-module-features', to: 'modules/cross-module'},

  // Reports lifts up to its own top-level section.
  {from: 'administration/reports',               to: 'reports-and-analytics/legacy'},

  // System Management + Access Permissions stay under administration/. No
  // move needed for either.
];

// ---- 2. Plan + execute ---------------------------------------------------

function isEmpty(dir) {
  if (!fs.existsSync(dir)) return true;
  return fs.readdirSync(dir).length === 0;
}

function gitMvDir(from, to) {
  const src = path.join(DOCS, from);
  const dst = path.join(DOCS, to);
  if (!fs.existsSync(src)) {
    console.log(`  · skip (missing): ${from}`);
    return;
  }
  const dstParent = path.dirname(dst);
  if (!fs.existsSync(dstParent)) {
    fs.mkdirSync(dstParent, {recursive: true});
  }
  if (fs.existsSync(dst) && !isEmpty(dst)) {
    throw new Error(`Destination ${to} already exists and is non-empty - aborting`);
  }
  // git mv preserves history; use -k to skip files that error individually.
  execSync(`git mv "${src}" "${dst}"`, {cwd: ROOT, stdio: 'inherit'});
}

function ensureCategoryJson(dir, label, position, customProps) {
  const target = path.join(DOCS, dir, '_category_.json');
  if (!fs.existsSync(path.dirname(target))) {
    fs.mkdirSync(path.dirname(target), {recursive: true});
  }
  const obj = {
    label,
    position,
    collapsible: true,
    collapsed: true,
    customProps,
  };
  fs.writeFileSync(target, JSON.stringify(obj, null, 2) + '\n');
  console.log(`  + _category_.json @ ${dir}`);
}

function listMarkdown(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
    if (entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listMarkdown(full));
    else if (entry.name.endsWith('.md')) out.push(full);
  }
  return out;
}

function buildRedirectMap() {
  const redirects = [];
  for (const m of MOVES) {
    const toDir = path.join(DOCS, m.to);
    const files = listMarkdown(toDir);
    for (const file of files) {
      const rel = path.relative(toDir, file).replace(/\\/g, '/');
      const stem = rel.replace(/\.md$/, '');
      redirects.push({
        from: '/' + m.from + '/' + stem,
        to:   '/' + m.to   + '/' + stem,
      });
    }
  }
  return redirects;
}

function main() {
  console.log(`migrate-ia: ${APPLY ? 'APPLY' : 'DRY RUN'} - see plans/help-menu-redesign.md`);
  console.log('');
  console.log('Section _category_.json files:');
  for (const s of SECTIONS) console.log(`  - docs/${s.dir}/_category_.json  (${s.label})`);
  console.log('');
  console.log('Module _category_.json files (under docs/modules/):');
  for (const m of MODULES) console.log(`  - docs/modules/${m.dir}/_category_.json  (${m.label})`);
  console.log('');
  console.log('Directory moves:');
  for (const mv of MOVES) console.log(`  docs/${mv.from}  →  docs/${mv.to}`);
  console.log('');

  if (!APPLY) {
    console.log('Dry run complete. Re-run with --apply to execute.');
    return;
  }

  // Working-tree guard: best-effort warning, not a blocker. Recovery is
  // `git reset --hard HEAD` plus `git clean -fd docs/modules docs/get-started`
  // because nothing here is committed yet.
  const dirty = execSync('git status --porcelain', {cwd: ROOT}).toString();
  if (dirty.trim()) {
    console.log('(working tree has uncommitted changes; proceeding because --apply was passed)');
  }

  // 1. Perform moves
  for (const mv of MOVES) {
    console.log(`mv: docs/${mv.from} → docs/${mv.to}`);
    gitMvDir(mv.from, mv.to);
  }

  // 2. Write section _category_.json files
  console.log('');
  console.log('Writing section gates …');
  for (const s of SECTIONS) {
    ensureCategoryJson(s.dir, s.label, s.position, s.customProps);
  }

  // 3. Write module _category_.json files
  console.log('');
  console.log('Writing module gates …');
  for (const m of MODULES) {
    ensureCategoryJson('modules/' + m.dir, m.label, m.position, m.customProps);
  }

  // 4. Emit redirect map
  console.log('');
  const redirects = buildRedirectMap();
  const redirectsPath = path.join(ROOT, 'data', 'redirects.json');
  if (!fs.existsSync(path.dirname(redirectsPath))) {
    fs.mkdirSync(path.dirname(redirectsPath), {recursive: true});
  }
  fs.writeFileSync(redirectsPath, JSON.stringify({version: 1, redirects}, null, 2) + '\n');
  console.log(`Wrote ${redirects.length} redirect(s) → data/redirects.json`);

  console.log('');
  console.log('migrate-ia: DONE. Next steps:');
  console.log('  1. Update sidebars.ts to point at the new tree (Phase 2 Slice B)');
  console.log('  2. Wire data/redirects.json into docusaurus.config.ts via @docusaurus/plugin-client-redirects');
  console.log('  3. Run: npm run validate:privileges && npm run lint:docs && npm run build');
  console.log('  4. Re-index ChromaDB: node server.js (in one shell) + npm run index-internal');
}

main();
