#!/usr/bin/env node
/**
 * Scaffold a new docs module so it starts life on the canonical 8-leaf
 * template. This creates ONLY the two things the rest of the pipeline can't
 * infer on its own:
 *
 *   1. an entry in static/module-overviews.json  (the module's gate identity -
 *      privilege / anyPrivilege - and its marketing copy), and
 *   2. docs/modules/<slug>/_category_.json       (the module root; roles stay
 *      open with NO privilege so the index page is reachable for the upsell
 *      flow - see scripts/audit-gates.js).
 *
 * It deliberately does NOT pre-create empty leaf folders: Docusaurus skips
 * empty autogenerated categories (they render no route), so an empty leaf is
 * invisible. Leaves appear as you add articles to them. The canonical leaf
 * set (labels, positions, gates) is applied automatically by the existing
 * pipeline once articles exist:
 *
 *   node scripts/write-subsection-categories.js   # label + position per leaf
 *   node scripts/restamp-subsection-gates.js      # canonical role gate per leaf
 *   node scripts/cascade-module-privilege.js      # push module privilege down
 *   npm run audit:gates                           # verify (must be clean)
 *
 * The 8 canonical leaves (Assign & Schedule is being deprecated - do not add
 * new content there):
 *   for-learners, for-managers, create-and-manage, features,
 *   reports-and-analytics, settings-and-permissions, best-practices,
 *   faqs-and-troubleshooting
 *
 * Usage:
 *   node scripts/new-module.js --slug loyalty --label "Loyalty" \
 *     --privilege rewards --position 160 \
 *     --tagline "Points, tiers, and reward redemption." \
 *     --description "Loyalty lets editors run points programs and learners redeem rewards."
 *
 *   # module gated by ANY of several privileges (like kpi-gamification):
 *   node scripts/new-module.js --slug engagement --label "Engagement" \
 *     --any-privilege kpi,streaks,xpPoints --position 170
 *
 * Idempotent-ish: refuses to overwrite an existing module. Re-run the
 * pipeline scripts above (not this one) to reconcile an existing module.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const MODULES_DIR = path.join(ROOT, 'docs', 'modules');
const OVERVIEWS_PATH = path.join(ROOT, 'static', 'module-overviews.json');
const KNOWN_PRIV_PATH = path.join(ROOT, 'data', 'known-privileges.json');

const ALL_ROLES = ['user', 'manager', 'editor', 'admin', 'orgadmin', 'lamadmin', 'superadmin'];

function fail(msg) {
  console.error('[new-module] ERROR: ' + msg);
  process.exit(1);
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) continue;
    const key = a.slice(2);
    const val = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : 'true';
    out[key] = val;
  }
  return out;
}

const args = parseArgs(process.argv.slice(2));

const slug = args.slug;
const label = args.label;
if (!slug) fail('--slug <kebab-case> is required');
if (!label) fail('--label "<Display Name>" is required');
if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(slug)) fail(`--slug "${slug}" must be kebab-case (a-z, 0-9, hyphens)`);

const privilege = args.privilege && args.privilege !== 'true' ? args.privilege : null;
const anyPrivilege = args['any-privilege'] && args['any-privilege'] !== 'true'
  ? args['any-privilege'].split(',').map((s) => s.trim()).filter(Boolean)
  : null;
if (privilege && anyPrivilege) fail('pass either --privilege or --any-privilege, not both');

// Validate privilege keys against the LMS snapshot (same list the build guard uses).
const known = new Set(JSON.parse(fs.readFileSync(KNOWN_PRIV_PATH, 'utf8')).privileges || []);
for (const p of [privilege, ...(anyPrivilege || [])].filter(Boolean)) {
  if (!known.has(p)) fail(`privilege "${p}" is not in data/known-privileges.json (add it there first, or fix the spelling)`);
}

const position = args.position && args.position !== 'true' ? parseInt(args.position, 10) : 999;
if (Number.isNaN(position)) fail('--position must be an integer');

const moduleDir = path.join(MODULES_DIR, slug);
const categoryPath = path.join(moduleDir, '_category_.json');

// --- guard: never clobber an existing module ---------------------------------
const overviews = JSON.parse(fs.readFileSync(OVERVIEWS_PATH, 'utf8'));
overviews.modules = overviews.modules || {};
if (fs.existsSync(categoryPath) || overviews.modules[slug]) {
  fail(`module "${slug}" already exists (docs/modules/${slug} and/or module-overviews entry). ` +
    'Reconcile it with the pipeline scripts, not new-module.js.');
}

// --- 1. static/module-overviews.json entry -----------------------------------
const gateIdentity = anyPrivilege ? {anyPrivilege} : privilege ? {privilege} : {};
overviews.modules[slug] = {
  label,
  tagline: args.tagline && args.tagline !== 'true' ? args.tagline : '',
  description: args.description && args.description !== 'true' ? args.description : '',
  keyFeatures: [],
  who: '',
  ...gateIdentity,
  ctaEmail: args.cta && args.cta !== 'true' ? args.cta : 'support@smartwinnr.com',
};
fs.writeFileSync(OVERVIEWS_PATH, JSON.stringify(overviews, null, 2) + '\n');

// --- 2. docs/modules/<slug>/_category_.json (root; open, NO privilege) --------
fs.mkdirSync(moduleDir, {recursive: true});
const category = {
  label,
  position,
  collapsible: true,
  collapsed: true,
  customProps: {roles: ALL_ROLES},
};
fs.writeFileSync(categoryPath, JSON.stringify(category, null, 2) + '\n');

// --- 3. docs/modules/<slug>/index.mdx (per-module overview + upsell page) -----
// Uniform across every module: renders <ModuleOverview slug="..."/>, which
// reads the static/module-overviews.json entry written above. audit-gates
// requires this file. Roles stay open (upsell page must be reachable).
const indexPath = path.join(moduleDir, 'index.mdx');
const tagline = overviews.modules[slug].tagline || '';
const indexFrontmatter = [
  '---',
  `id: module-${slug}`,
  `title: ${label}`,
  `description: '${tagline.replace(/'/g, "''")}'`,
  `slug: /modules/${slug}/`,
  'displayed_sidebar: tutorialSidebar',
  'hide_title: true',
  'hide_table_of_contents: true',
  'customProps:',
  '  roles:',
  ...ALL_ROLES.map((r) => `    - ${r}`),
  'tags:',
  `  - ${slug}`,
  '---',
  '',
  "import ModuleOverview from '@site/src/components/Modules/ModuleOverview';",
  '',
  `<ModuleOverview slug="${slug}" />`,
  '',
].join('\n');
fs.writeFileSync(indexPath, indexFrontmatter);

// --- done: print the follow-up runbook ---------------------------------------
const gateDesc = anyPrivilege ? `anyPrivilege [${anyPrivilege.join(', ')}]` : privilege ? `privilege ${privilege}` : 'no privilege (open module)';
console.log(`[new-module] created module "${slug}" (${label}), gate: ${gateDesc}`);
console.log('  + static/module-overviews.json entry');
console.log(`  + docs/modules/${slug}/_category_.json`);
console.log(`  + docs/modules/${slug}/index.mdx`);
console.log('');
console.log('Next steps:');
console.log(`  1. Add articles under docs/modules/${slug}/<leaf>/ using the canonical leaf names:`);
console.log('       for-learners  for-managers  create-and-manage  features');
console.log('       reports-and-analytics  settings-and-permissions  best-practices  faqs-and-troubleshooting');
console.log('     (the authoring wizard offers these automatically; do NOT add assign-and-schedule - deprecating)');
console.log('  2. Stamp canonical labels/positions and gates:');
console.log('       node scripts/write-subsection-categories.js');
console.log('       node scripts/restamp-subsection-gates.js');
console.log('       node scripts/cascade-module-privilege.js');
console.log('  3. Verify:  npm run audit:gates   (must report 0 warnings, 0 failures)');
